Calculations
========================================================

Calculating the area burned per year & the number of arrivals (i.e., new fires) per year

```{r}
omnr <- read.csv("OMNR_data.csv", header=TRUE)

# create subset omnr.clean == only fires in the Intensive and Measured Zones & caused by Lightening
omnr.clean <- subset(omnr, subset = (omnr$FIRE_MGT_ZONE == "MEA" | omnr$FIRE_MGT_ZONE == "INT"))
                     
omnr.3E <- subset(omnr.clean, subset = (omnr.clean$LATITUDE>=48 & omnr.clean$LATITUDE<=51) & (omnr.clean$LONGITUDE<=-80 & omnr.clean$LONGITUDE>=-86))

omnr.3W <- subset(omnr.clean, subset = (omnr.clean$LATITUDE>=48 & omnr.clean$LATITUDE<=51) & (omnr.clean$LONGITUDE<=-88 & omnr.clean$LONGITUDE>=-92))

omnr.3S <- subset(omnr.clean, subset = (omnr.clean$LATITUDE>=51 & omnr.clean$LATITUDE<=53) & (omnr.clean$LONGITUDE<=-88 & omnr.clean$LONGITUDE>=-96))

omnr.total <- rbind(omnr.3E, omnr.3W, omnr.3S)


A <- sum(omnr.total$FINAL_SIZE)

A

# area burned per year
At <- aggregate(omnr.total$FINAL_SIZE, by=list(omnr.total$FIRE_YEAR),sum)

# rename columns
names(At) <- c("Year", "Area (ha)")

At

# number of arrivals per year
Nt <- aggregate(omnr.total$FINAL_SIZE, by=list(omnr.total$FIRE_YEAR),length)

## Length here means how long is the vector, i.e., how many data points are in the vector, therefore, in this case it is more akin to asking “how many” than “how long?”

# rename columns
names(Nt) <- c("Year", "Fires")

Nt

N <- sum(Nt$Fires)

N

omnr.small <- subset(omnr.total, subset = omnr.total$FINAL_SIZE < 3)
                     
small <- aggregate(omnr.small$FINAL_SIZE, by=list(omnr.small$FIRE_YEAR),length)

names(small) <- c("Year", "Fires")

small <- sum(small$Fires)

small

percent.small <- (small/N)*100

percent.small

omnr.big <- subset(omnr.total, subset = omnr.total$FINAL_SIZE > 200)

big <- aggregate(omnr.big$FINAL_SIZE, by=list(omnr.big$FIRE_YEAR),length)

names(big) <- c("Year", "Fires")

big <- sum(big$Fires)

big

percent.big <- (big/N)*100

percent.big

suppressed <- N-(big + small)

suppressed

percent.suppressed <- (suppressed/N)*100

percent.suppressed
```

```{r}
print(sessionInfo(), locale = FALSE)
```
